// Convex schema description for the miniapp.
// This file documents the `products` table shape and recommended indexes.

export interface Product {
  // Primary key generated by Convex (string)
  _id?: string;

  // Basic product info
  name: string;
  brand: string;
  model?: string | null;
  price: number;
  storage?: string | null; // e.g. "128GB"
  condition?: string | null; // e.g. "New", "Like New", "Used"

  // Image(s)
  images?: string[] | null;
  main_image_url?: string | null;

  // Flags for filtering / presentation
  isFeatured?: boolean | null; // new field requested
  is_accessory?: boolean | null;
  in_stock?: boolean | null;
  is_popular?: boolean | null;
  is_premium?: boolean | null;

  // Optional meta
  createdAt?: number | null;
  updatedAt?: number | null;
}

// Recommended indexes (applied in Convex dashboard or migrations):
// 1) Index on `brand` for fast brand filtering
// 2) Index on `isFeatured` (or `is_featured`) to quickly return featured items
// Example (pseudocode): db.table('products').createIndex(['brand']);
// Example (pseudocode): db.table('products').createIndex(['isFeatured']);

export default {
  products: {
    type: "table",
    fields: {
      name: "string",
      brand: "string",
      model: "string?",
      price: "number",
      storage: "string?",
      condition: "string?",
      images: "string[]?",
      main_image_url: "string?",
      isFeatured: "boolean?",
      is_accessory: "boolean?",
      in_stock: "boolean?",
      is_popular: "boolean?",
      is_premium: "boolean?",
      createdAt: "number?",
      updatedAt: "number?",
    },
    // logical indexes documented here for maintainers
    indexes: [{ fields: ["brand"] }, { fields: ["isFeatured"] }],
  },
};
