// Minimal placeholder for Convex generated API surface.
// This file provides a small `api` object so imports elsewhere in the app compile.
// In a real Convex workflow this file is generated by `convex dev`.

// Minimal generated API shim for Convex server functions.
// Update this file by running `convex dev` in a real development workflow.
export const api: any = {
  products: {
    // Points to the server query defined in `convex/products.ts`
    listAllProducts: {
      // marker so the client-side code can pass this into `useQuery`
      name: "products.listAllProducts",
    },
  },
  favorites: {},
  search: {},
  sessions: {},
  phoneActions: {},
  affiliates: {},
};
